config/routes.rb
Rails.application.routes.draw do
  
  resources :products

  resources :profiles

   resources :categories
  get 'site/home'

  get 'site/contact'

  devise_for :users, controllers: { registrations: "registrations"}
  resources :courses

  get 'site/hello'
  get 'site/contact'
  get 'site/goodbye'

   root 'courses#index'

end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController

  load_and_authorize_resource 

  before_action :authenticate_user!, only: [:edit, :new, :destroy]
  before_action :set_course, only: [:show]

  # GET /courses
  # GET /courses.json
  def index
    if (!current_user.nil?) && (current_user.role? "trainer") 
      @courses = Course.all  # Course.where('user_id = ?', current_user.id)
    else 
      @courses = Course.all 
    end
  end

  # GET /courses/1
  # GET /courses/1.json
  def show
  end

  # GET /courses/new
  def new
    @course = Course.new
  end

  # GET /courses/1/edit
  def edit
    @course = current_user.courses.find(params[:id])
  end

  # POST /courses
  # POST /courses.json
  def create
    @course = Course.new(course_params)

    @course.user_id = current_user.id

    respond_to do |format|
      if @course.save
        format.html { redirect_to @course, notice: 'Course was successfully created.' }
        format.json { render :show, status: :created, location: @course }
      else
        format.html { render :new }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /courses/1
  # PATCH/PUT /courses/1.json
  def update
    @course.user_id = current_user.id
    respond_to do |format|
      if @course.update(course_params)
        format.html { redirect_to @course, notice: 'Course was successfully updated.' }
        format.json { render :show, status: :ok, location: @course }
      else
        format.html { render :edit }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /courses/1
  # DELETE /courses/1.json
  def destroy
    @course.destroy
    respond_to do |format|
      format.html { redirect_to courses_url, notice: 'Course was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_course
      @course = Course.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def course_params
      params.require(:course).permit(:name,:category_id)
    end
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/views/courses/_form.html.erb
<%= form_for(@course) do |f| %>
  <% if @course.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@course.errors.count, "error") %> prohibited this course from being saved:</h2>

      <ul>
      <% @course.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>

<div class="field">
 <%= f.label :Select_Category %><br>
  <%= f.collection_select :category_id, Category.all, :id, :name, prompt:"Select Category"%></br>
</div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/courses/edit.html.erb
<h1>Editing Course</h1>

<%= render 'form' %>

<%= link_to 'Show', @course %> |
<%= link_to 'Back', courses_path %>

app/views/courses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Courses (<%= @courses.length %>)</h1>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Catregory Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @courses.each do |course| %>
      <tr>
        <td><%= course.name %></td>
        
        <%if !course.category.nil? %> <!-- unless -->
        <td><%= link_to course.category.try(:name), category_path(course.category) %></td>
        <%else%>
        <td>No Catregory</td>
        <%end%>

        <td><%= link_to 'Show', course %></td>
       
        <% if can? :update, course %>
          <td><%= link_to 'Edit', edit_course_path(course) %></td>
        <% end %>
       
        <% if can? :destroy, course %>
         <td><%= link_to 'Destroy', course, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
     
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<% if can? :create, Course.new %>
  <%= link_to new_course_path, class: "btn btn-primary" do %>
  <i class="glyphicon glyphicon-plus"></i>Add New Course
  <%end%>
<% end %>

app/views/courses/new.html.erb
<h1>New Course</h1>

<%= render 'form' %>

<%= link_to 'Back', courses_path %>

app/views/courses/show.html.erb
<p id="notice"><%= notice %></p>


<div class="container">
<p>
  <strong>Name:</strong>
  <%= @course.name %>
</p>

<p>
  <strong>Category Name:</strong>
  <%= link_to @course.category.name, category_path(@course.category)%>
</p>

<p>
<strong>Trainer Name:</strong>
<% if (!@course.user.nil?) && (!@course.user.profile.nil?)%>
<%= link_to @course.user.first_name, profile_path(@course.user.profile) %>
<%end%>
</p>

<% if can? :update, @course %>
	<%= link_to 'Edit', edit_course_path(@course) %> |
<% end %>

<%= link_to 'Back', courses_path %>
</div>