config/routes.rb
Rails.application.routes.draw do
  
  resources :products

  resources :profiles

   resources :categories
  get 'site/home'

  get 'site/contact'

  devise_for :users, controllers: { registrations: "registrations"}
  resources :courses

  get 'site/hello'
  get 'site/contact'
  get 'site/goodbye'

   root 'courses#index'

end

app/models/category.rb
class Category < ActiveRecord::Base
	belongs_to :master_category
	has_many :courses, dependent: :destroy # :nullify 
	# method argument : (colon) before ex - has_many :courses
	# option for method : (colon) after ex - dependent: 
	# value for the option : (colon) before  ex - :destroy 

	validates_presence_of :name, message: "You should give a name"
    validates_numericality_of :master_category_id, message: "id is mandatory"
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
	load_and_authorize_resource
  before_action :authenticate_user!, except: [:index,:show]
	
	def index
		@categories = Category.all
	end

    def new
	    @category = Category.new
    end
		
	def edit
		@category = Category.find(params[:id])
    end

    def update
		@category = Category.find(params[:id])
		if @category.update_attributes(category_params)
			redirect_to category_path(@category), notice: "successfully updated"
        end
    end


    def destroy
		@category = Category.find(params[:id])
		if @category.destroy
			redirect_to categories_path(@category), notice: "successfully deleted"
        end   
    end 

    def show
    	@category = Category.find(params[:id])
        end

    def create
    	@category = Category.new(category_params)
        	if @category.save
        		redirect_to categories_path,  notice: 'Category was successfully created.'
        	else
        		render action: "new"
        	end
        end


    def category_params
    	params[:category].permit(:master_category_id, :name)
        end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<%= form_for @category do |f| %>

<% if @category.errors.any? %>
<h3>These are errors.</h3>
<ul>
	<%@category.errors.full_messages.each do |msg|%>
	<li><%= msg%></li>
	<%end%>


</ul>
<%end%>

<%= f.label :master_category %><br/>
<%= f.collection_select :master_category_id, MasterCategory.all, :id, :name, prompt:"select Master Category"%></br>
<%= f.label :name %><br/>
<%= f.text_field :name%><br/>
<%= f.submit "Submit"%>


	<%end%>

app/views/categories/edit.html.erb
<h2>Edit Category</h2>
<%=render "form"%>
<br/>
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<h2>List of Category</h2>

<table>
	<thead>
		<tr>
			<th>Name</th>
			<th>Master Category</th>

		</tr>
<tbody>
	
<%@categories.each do |category|%>

<tr>
    <td><%=link_to category.name, category_path(category) %></td>
	<td><%= category.master_category.try(:name) %></td>
	<%if (user_signed_in? && (can? :update,category))%>
	 <td><%= link_to 'Edit', edit_category_path(category) %></td>
	 <%end%>
</tr>
<%end%>

</tbody>


	</thead>



</table>
<br/>
<%if (user_signed_in?) && (can? :create, Category.new)%>
<%= link_to 'Add', new_category_path %>
    
    <%end%>

app/views/categories/new.html.erb
<h2>Add Category</h2>
<%=render "form"%>

app/views/categories/show.html.erb
<h2><%= @category.name%></h2>

<%if @category.courses.empty?%>
	
	<p>No course found for this category</p>

	<%else%>
	<ol>
	
	<% @category.courses.each do |course|%>
     	<li><%= link_to course.name, course_path(course)%></li>
	<%end%>
    
    </ol>
<%end%>

<%if (user_signed_in?) && (can? :destroy, @category )%>
<%= link_to 'Destroy', categories_path(@category), method: :delete, data: { confirm: 'Are you sure?' } %>
<%end%>

<%= link_to 'Back', categories_path %>